function getRandomArbitrary(min, max) {
  return Math.floor((Math.random() * (max - min) + min)).toString()
}
function sample(array) {
  return array[Math.floor ( Math.random() * array.length )]
}
const listNames = ['Mario Gutierrez', 'Franco Cuevas', 'Javier Mendoza', 'Miguel Moreira', 'Luis Rodriguez', 'Pedro Ramirez', 'Maria de la Rosa']
const divisionNames= ['Ceo', 'Strategy', 'Producto', 'Direccion general', 'Operaciones']

const STORE = [
  {
    key: "1",
    division: sample(divisionNames),
    divisionSuperior: sample(divisionNames),
    colaboradores: getRandomArbitrary(1, 11),
    nivel: getRandomArbitrary(1, 11),
    subdivisiones: getRandomArbitrary(1, 11),
    embajadores: sample(listNames),
  },
  {
    key: "2",
    division: sample(divisionNames),
    divisionSuperior: sample(divisionNames),
    colaboradores: getRandomArbitrary(1, 11),
    nivel: getRandomArbitrary(1, 11),
    subdivisiones: getRandomArbitrary(1, 11),
    embajadores: sample(listNames),
  },
  {
    key: "3",
    division:sample(divisionNames),
    divisionSuperior: sample(divisionNames),
    colaboradores: getRandomArbitrary(1, 11),
    nivel: getRandomArbitrary(1, 11),
    subdivisiones: getRandomArbitrary(1, 11),
    embajadores: sample(listNames),
  },
  {
    key: "4",
    division:sample(divisionNames),
    divisionSuperior: sample(divisionNames),
    colaboradores: getRandomArbitrary(1, 11),
    nivel: getRandomArbitrary(1, 11),
    subdivisiones: getRandomArbitrary(1, 11),
    embajadores: sample(listNames),
  },
  {
    key: "5",
    division:sample(divisionNames),
    divisionSuperior: sample(divisionNames),
    colaboradores: getRandomArbitrary(1, 11),
    nivel: getRandomArbitrary(1, 11),
    subdivisiones: getRandomArbitrary(1, 11),
    embajadores: sample(listNames),
  },
  {
    key: "6",
    division:sample(divisionNames),
    divisionSuperior: sample(divisionNames),
    colaboradores: getRandomArbitrary(1, 11),
    nivel: getRandomArbitrary(1, 11),
    subdivisiones: getRandomArbitrary(1, 11),
    embajadores: sample(listNames),
  },
  {
    key: "7",
    division:sample(divisionNames),
    divisionSuperior: sample(divisionNames),
    colaboradores: getRandomArbitrary(1, 11),
    nivel: getRandomArbitrary(1, 11),
    subdivisiones: getRandomArbitrary(1, 11),
    embajadores: sample(listNames),
  },
  {
    key: "8",
    division:sample(divisionNames),
    divisionSuperior: sample(divisionNames),
    colaboradores: getRandomArbitrary(1, 11),
    nivel: getRandomArbitrary(1, 11),
    subdivisiones: getRandomArbitrary(1, 11),
    embajadores: sample(listNames),
  },
  {
    key: "9",
    division:sample(divisionNames),
    divisionSuperior: sample(divisionNames),
    colaboradores: getRandomArbitrary(1, 11),
    nivel: getRandomArbitrary(1, 11),
    subdivisiones: getRandomArbitrary(1, 11),
    embajadores: sample(listNames),
  },
  {
    key: "10",
    division:sample(divisionNames),
    divisionSuperior: sample(divisionNames),
    colaboradores: getRandomArbitrary(1, 11),
    nivel: getRandomArbitrary(1, 11),
    subdivisiones: getRandomArbitrary(1, 11),
    embajadores: sample(listNames),
  },
  {
    key: "11",
    division:sample(divisionNames),
    divisionSuperior: sample(divisionNames),
    colaboradores: getRandomArbitrary(1, 11),
    nivel: getRandomArbitrary(1, 11),
    subdivisiones: getRandomArbitrary(1, 11),
    embajadores: sample(listNames),
  },
  {
    key: "12",
    division:sample(divisionNames),
    divisionSuperior: sample(divisionNames),
    colaboradores: getRandomArbitrary(1, 11),
    nivel: getRandomArbitrary(1, 11),
    subdivisiones: getRandomArbitrary(1, 11),
    embajadores: sample(listNames),
  },
  {
    key: "13",
    division:sample(divisionNames),
    divisionSuperior: sample(divisionNames),
    colaboradores: getRandomArbitrary(1, 11),
    nivel: getRandomArbitrary(1, 11),
    subdivisiones: getRandomArbitrary(1, 11),
    embajadores: sample(listNames),
  },
  {
    key: "14",
    division:sample(divisionNames),
    divisionSuperior: sample(divisionNames),
    colaboradores: getRandomArbitrary(1, 11),
    nivel: getRandomArbitrary(1, 11),
    subdivisiones: getRandomArbitrary(1, 11),
    embajadores: sample(listNames),
  },
  {
    key: "15",
    division:sample(divisionNames),
    divisionSuperior: sample(divisionNames),
    colaboradores: getRandomArbitrary(1, 11),
    nivel: getRandomArbitrary(1, 11),
    subdivisiones: getRandomArbitrary(1, 11),
    embajadores: sample(listNames),
  },
  {
    key: "16",
    division:sample(divisionNames),
    divisionSuperior: sample(divisionNames),
    colaboradores: getRandomArbitrary(1, 11),
    nivel: getRandomArbitrary(1, 11),
    subdivisiones: getRandomArbitrary(1, 11),
    embajadores: sample(listNames),
  },
  {
    key: "17",
    division:sample(divisionNames),
    divisionSuperior: sample(divisionNames),
    colaboradores: getRandomArbitrary(1, 11),
    nivel: getRandomArbitrary(1, 11),
    subdivisiones: getRandomArbitrary(1, 11),
    embajadores: sample(listNames),
  },
  {
    key: "18",
    division:sample(divisionNames),
    divisionSuperior: sample(divisionNames),
    colaboradores: getRandomArbitrary(1, 11),
    nivel: getRandomArbitrary(1, 11),
    subdivisiones: getRandomArbitrary(1, 11),
    embajadores: sample(listNames),
  },
  {
    key: "19",
    division:sample(divisionNames),
    divisionSuperior: sample(divisionNames),
    colaboradores: getRandomArbitrary(1, 11),
    nivel: getRandomArbitrary(1, 11),
    subdivisiones: getRandomArbitrary(1, 11),
    embajadores: sample(listNames),
  },
  {
    key: "20",
    division:sample(divisionNames),
    divisionSuperior: sample(divisionNames),
    colaboradores: getRandomArbitrary(1, 11),
    nivel: getRandomArbitrary(1, 11),
    subdivisiones: getRandomArbitrary(1, 11),
    embajadores: sample(listNames),
  },
  {
    key: "21",
    division:sample(divisionNames),
    divisionSuperior: sample(divisionNames),
    colaboradores: getRandomArbitrary(1, 11),
    nivel: getRandomArbitrary(1, 11),
    subdivisiones: getRandomArbitrary(1, 11),
    embajadores: sample(listNames),
  },
  {
    key: "22",
    division:sample(divisionNames),
    divisionSuperior: sample(divisionNames),
    colaboradores: getRandomArbitrary(1, 11),
    nivel: getRandomArbitrary(1, 11),
    subdivisiones: getRandomArbitrary(1, 11),
    embajadores: sample(listNames),
  },
  {
    key: "23",
    division:sample(divisionNames),
    divisionSuperior: sample(divisionNames),
    colaboradores: getRandomArbitrary(1, 11),
    nivel: getRandomArbitrary(1, 11),
    subdivisiones: getRandomArbitrary(1, 11),
    embajadores: sample(listNames),
  },
  {
    key: "24",
    division:sample(divisionNames),
    divisionSuperior: sample(divisionNames),
    colaboradores: getRandomArbitrary(1, 11),
    nivel: getRandomArbitrary(1, 11),
    subdivisiones: getRandomArbitrary(1, 11),
    embajadores: sample(listNames),
  },
  {
    key: "25",
    division:sample(divisionNames),
    divisionSuperior: sample(divisionNames),
    colaboradores: getRandomArbitrary(1, 11),
    nivel: getRandomArbitrary(1, 11),
    subdivisiones: getRandomArbitrary(1, 11),
    embajadores: sample(listNames),
  },
  {
    key: "26",
    division:sample(divisionNames),
    divisionSuperior: sample(divisionNames),
    colaboradores: getRandomArbitrary(1, 11),
    nivel: getRandomArbitrary(1, 11),
    subdivisiones: getRandomArbitrary(1, 11),
    embajadores: sample(listNames),
  },
  {
    key: "27",
    division:sample(divisionNames),
    divisionSuperior: sample(divisionNames),
    colaboradores: getRandomArbitrary(1, 11),
    nivel: getRandomArbitrary(1, 11),
    subdivisiones: getRandomArbitrary(1, 11),
    embajadores: sample(listNames),
  },
  {
    key: "28",
    division:sample(divisionNames),
    divisionSuperior: sample(divisionNames),
    colaboradores: getRandomArbitrary(1, 11),
    nivel: getRandomArbitrary(1, 11),
    subdivisiones: getRandomArbitrary(1, 11),
    embajadores: sample(listNames),
  },
  {
    key: "29",
    division:sample(divisionNames),
    divisionSuperior: sample(divisionNames),
    colaboradores: getRandomArbitrary(1, 11),
    nivel: getRandomArbitrary(1, 11),
    subdivisiones: getRandomArbitrary(1, 11),
    embajadores: sample(listNames),
  },
  {
    key: "30",
    division:sample(divisionNames),
    divisionSuperior: sample(divisionNames),
    colaboradores: getRandomArbitrary(1, 11),
    nivel: getRandomArbitrary(1, 11),
    subdivisiones: getRandomArbitrary(1, 11),
    embajadores: sample(listNames),
  },
  {
    key: "31",
    division:sample(divisionNames),
    divisionSuperior: sample(divisionNames),
    colaboradores: getRandomArbitrary(1, 11),
    nivel: getRandomArbitrary(1, 11),
    subdivisiones: getRandomArbitrary(1, 11),
    embajadores: sample(listNames),
  },
  {
    key: "32",
    division:sample(divisionNames),
    divisionSuperior: sample(divisionNames),
    colaboradores: getRandomArbitrary(1, 11),
    nivel: getRandomArbitrary(1, 11),
    subdivisiones: getRandomArbitrary(1, 11),
    embajadores: sample(listNames),
  },
  {
    key: "33",
    division:sample(divisionNames),
    divisionSuperior: sample(divisionNames),
    colaboradores: getRandomArbitrary(1, 11),
    nivel: getRandomArbitrary(1, 11),
    subdivisiones: getRandomArbitrary(1, 11),
    embajadores: sample(listNames),
  },
  {
    key: "34",
    division:sample(divisionNames),
    divisionSuperior: sample(divisionNames),
    colaboradores: getRandomArbitrary(1, 11),
    nivel: getRandomArbitrary(1, 11),
    subdivisiones: getRandomArbitrary(1, 11),
    embajadores: sample(listNames),
  },
  {
    key: "35",
    division:sample(divisionNames),
    divisionSuperior: sample(divisionNames),
    colaboradores: getRandomArbitrary(1, 11),
    nivel: getRandomArbitrary(1, 11),
    subdivisiones: getRandomArbitrary(1, 11),
    embajadores: sample(listNames),
  },
  {
    key: "36",
    division:sample(divisionNames),
    divisionSuperior: sample(divisionNames),
    colaboradores: getRandomArbitrary(1, 11),
    nivel: getRandomArbitrary(1, 11),
    subdivisiones: getRandomArbitrary(1, 11),
    embajadores: sample(listNames),
  },
  {
    key: "37",
    division:sample(divisionNames),
    divisionSuperior: sample(divisionNames),
    colaboradores: getRandomArbitrary(1, 11),
    nivel: getRandomArbitrary(1, 11),
    subdivisiones: getRandomArbitrary(1, 11),
    embajadores: sample(listNames),
  },
  {
    key: "38",
    division:sample(divisionNames),
    divisionSuperior: sample(divisionNames),
    colaboradores: getRandomArbitrary(1, 11),
    nivel: getRandomArbitrary(1, 11),
    subdivisiones: getRandomArbitrary(1, 11),
    embajadores: sample(listNames),
  },
  {
    key: "39",
    division:sample(divisionNames),
    divisionSuperior: sample(divisionNames),
    colaboradores: getRandomArbitrary(1, 11),
    nivel: getRandomArbitrary(1, 11),
    subdivisiones: getRandomArbitrary(1, 11),
    embajadores: sample(listNames),
  },
  {
    key: "40",
    division:sample(divisionNames),
    divisionSuperior: sample(divisionNames),
    colaboradores: getRandomArbitrary(1, 11),
    nivel: getRandomArbitrary(1, 11),
    subdivisiones: getRandomArbitrary(1, 11),
    embajadores: sample(listNames),
  },
  
  
];
export default STORE;
